; PlatformIO Project Configuration File
; Lab Task 7 — Multi-Component Security System
; ADA University · Embedded Systems
;
; Build: PlatformIO: Build (Ctrl+Alt+B)
; Upload: PlatformIO: Upload (Ctrl+Alt+U)
; Monitor: PlatformIO: Serial Monitor (Ctrl+Alt+S)

[env:uno]
platform        = atmelavr
board           = uno
framework       = arduino

monitor_speed   = 115200
monitor_filters = default, time
upload_port  = COM6      ; or /dev/ttyUSB0 on Linux/macOS
monitor_port = COM6
; ---- Library dependencies ----
; PlatformIO will auto-download these into .pio/libdeps/uno/ on first build.
lib_deps =
    chris--a/Keypad@^3.1.1
    miguelbalboa/MFRC522@^1.4.10
    z3t0/IRremote@^4.4.0

; ---- Build flags ----
; Enable IRremote feedback LED on pin 13 (the on-board LED) when an IR frame
; is decoded. Comment out if you don't want the visual feedback.
build_flags =
    -D ENABLE_LED_FEEDBACK